### ISSUE TITLE
Dependencies view empty / now rows written to cassandra

### ISSUE THREAD

**Issue by maihacke** [openzipkin/zipkin-dependencies#22]
1. I did a small test setup on my local machine with openzipkin/docker-zipkin
2. Added some data from a spring boot app
3. Traces are visible in zipkin web ui
4. Then i tried to run zipkin-dependencies-spark with gradlew run against my local dockerized cassandra db
5. no errors in the log. but it shows that no rows were written to cassandra and - dependencie view stays empty... (TableWriter: Wrote 0 rows to zipkin.dependencies)

**Comment by adriancole** [comment]
To offer a solution to this and similar other problems. zipkin-java is formalizing, and it has a [DependencyLinker](https://github.com/openzipkin/zipkin-java/blob/0.20.1/zipkin/src/main/java/zipkin/internal/DependencyLinker.java) which properly aggregates one or more traces.

It requires a conversion step to turn a span into the input to the [dependency linker](https://github.com/openzipkin/zipkin-java/blob/0.20.1/zipkin/src/main/java/zipkin/internal/DependencyLinkSpan.java). This is to allow some storage apis to pull less data (as opposed to the entire span which includes annotations not relevant). For example, the mysql backend only brings back [partial data](https://github.com/openzipkin/zipkin-java/blob/0.20.1/zipkin-storage/jdbc/src/main/java/zipkin/storage/jdbc/DependencyLinkSpanIterator.java) that's needed. 

Meanwhile, Zipkin recently includes the ability to pull all traces given a time interval expressed as endTs, lookback. This means that you can do a storage-agnostic implementation of dependency linking.

My suggestion is to re-use the linker library, as it is easy to benchmark and can be made even more efficient if it isn't currently. By re-using this, we can offer a consistent experience, regardless of whether spark is used to manage the large amount of input. Note re-use of the library could be direct (ex in the spark job), or exposing an on-demand linking endpoint on the zipkin server. There are pros and cons to each.

Regardless, if someone would like to start on this, I'd help support. Otherwise, it might be a while for me to get to it because I'm working on finishing the 1.0 release of zipkin-java.

**Comment by adriancole** [comment]
the code has been re-written, so please re-open if there's an issue

**Comment by tal-ni** [comment]
I'm using MySql as the database layer and i have many traces coming from different services what are the steps I need to follow in order to see dependencies graph?

**Comment by adriancole** [comment]
@tal-ni I don't see a relationship between this issue and your question. Probably better to start wit gitter as there's likely something wrong with your instrumentation. https://gitter.im/openzipkin/zipkin

**Comment by tal-ni** [comment]
Hi adrian,

I see all my traces and spans visualized ok in the traces tab, it's just the dependencies tab not showing the relations diagram even though I'm running the zipkin-dependencies spark job.  any help will be appreciated.

**Comment by adriancole** [comment]
@tal-ni happy to help, but please stop adding message to an unrelated issue.
